name: gtk-bh-5-6-v3
channels:
  - conda-forge
  - defaults
dependencies:
  - graphviz
  - ipykernel
  - ipywidgets
  - joblib
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - numba
  - pip
  - pydotplus
  - python=3.12
  - scikit-learn
  - scipy
  - seaborn
  - shap
  - statsmodels
  - tqdm
  - yaml
  - lime
  - ipython

