name: gtk-bh-8                                                                                                                               
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.3
  - tensorflow
  - keras
  - pandas
  - jupyter
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - statsmodels
  - pip
  - ipywidgets
  - ipykernel
  - pillow
  - pydotplus

  