name: gtk-blackhat                                                                                                                               
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - statsmodels
  - pip
  - ydata-profiling
  - ipywidgets
  - pydotplus
  - pmdarima
  - numba==0.58.1 
  - jupyter
  
